### ISSUE TITLE
Feat- 쿠폰 발급 테스트 코드 개선

### ISSUE THREAD

**Issue by codesejin** [f-lab-edu/off-coupon#9]
# TODO
- [x] 중복 테스트 코드 개선
- [x] 분산락 컴포넌트 클래스 테스트 추가
- [x] 쿠폰 발급 컨트롤러 테스트 추가
